### PR TITLE
Add focus event listeners to show/hide dropdown

### PR DESCRIPTION
**Pull request by moomoohk**

### CODE REVIEW

**Comment by moomoohk** [comment]
Includes #6

**Comment by mattmezza** [comment]
FYI https://github.com/mattmezza/bulmahead/commit/47e7cad9b9a627963ed2f6f81888ba9109f3793b had to add a delay to focus out to let the click go through.
Maybe there's a better solution to all this.

**Comment by moomoohk** [comment]
It seems to be working fine for me (before your change)
Am I missing something?
ezgif-2-3a59f192cf4d

**Comment by moomoohk** [comment]
Oh, you meant when clicking on the options. I see the problem now. I'll see if I can figure out an elegant fix

**Comment by moomoohk** [comment]
Submitted #11

**Pull request merged**
